name: build-6.2

on:
  push:
    branches:
      - "releases/*"
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-20.04
          - macos-11
        redis:
          - "6.2.13"
          - "6.2.12"
          - "6.2.11"
          - "6.2.10"
          - "6.2.9"
          - "6.2.8"
          - "6.2.7"
          - "6.2.6"
          - "6.2.5"
          - "6.2.4"
          - "6.2.3"
          - "6.2.2"
          - "6.2.1"
          - "6.2.0"
    steps:
      - uses: actions/checkout@v4
      - name: build
        shell: bash
        run: ./build-redis-with-openssl1.1.sh "$REDIS_VERSION"
        env:
          REDIS_VERSION: ${{ matrix.redis }}

      - name: upload
        run: |
          ACTIONS_VERSION=v$(jq -r .version < "$GITHUB_WORKSPACE/package.json")
          OS=$(uname | tr '[:upper:]' '[:lower:]')
          mv "$RUNNER_TEMP/redis-bin.tar.zstd" "$RUNNER_TEMP/redis-$REDIS_VERSION-$OS-x64.tar.zstd"
          gh release upload --clobber "$ACTIONS_VERSION" "$RUNNER_TEMP/redis-$REDIS_VERSION-$OS-x64.tar.zstd"
        env:
          REDIS_VERSION: ${{ matrix.redis }}
          GITHUB_TOKEN: ${{ github.token }}
