name: build Redis 8.0

on:
  push:
    branches:
      - "releases/*"
  workflow_dispatch:

jobs:
  build:
    timeout-minutes: 16
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-22.04
          - ubuntu-22.04-arm
          - macos-14
          - macos-13
        redis:
          - "8.0.3"
          - "8.0.2"
          - "8.0.1"
          - "8.0.0"
    permissions:
      contents: write
      id-token: write
      attestations: write
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          persist-credentials: "false"
      - name: build
        shell: bash
        run: ./build-redis-with-openssl3.sh "$REDIS_VERSION"
        env:
          REDIS_VERSION: ${{ matrix.redis }}

      - name: upload
        run: |
          ACTIONS_VERSION=v$(jq -r .version < "$GITHUB_WORKSPACE/package.json")
          REDIS_OS=$(uname -s | tr '[:upper:]' '[:lower:]')
          case "$(uname -m)" in
              "x86_64")
                  REDIS_ARCH="x64"
                  ;;
              "arm64" | "aarch64")
                  REDIS_ARCH="arm64"
                  ;;
              *)
                  echo "unsupported architecture: $(uname -m)"
                  exit 1
                  ;;
          esac
          mv "$RUNNER_TEMP/redis-bin.tar.zstd" "$RUNNER_TEMP/redis-$REDIS_VERSION-$REDIS_OS-$REDIS_ARCH.tar.zstd"
          gh release upload --clobber "$ACTIONS_VERSION" "$RUNNER_TEMP/redis-$REDIS_VERSION-$REDIS_OS-$REDIS_ARCH.tar.zstd"
        env:
          REDIS_VERSION: ${{ matrix.redis }}
          GITHUB_TOKEN: ${{ github.token }}
      - uses: actions/attest-build-provenance@e8998f949152b193b063cb0ec769d69d929409be # v2.4.0
        with:
          subject-path: ${{ runner.temp }}/*.tar.zstd
