name: build-6.2

on:
  push:
    branches:
      - "releases/*"
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-18.04
          - macos-10.15
        redis:
          - "6.2.5"
          - "6.2.4"
          - "6.2.3"
          - "6.2.2"
          - "6.2.1"
          - "6.2.0"
    steps:
      - uses: actions/checkout@v2
      - name: build
        shell: bash
        run: ./build-redis-with-openssl.sh "$REDIS_VERSION"
        env:
          REDIS_VERSION: ${{ matrix.redis }}

      - uses: kheiakiyama/install-azcopy-action@v1
        with:
          version: "v10"
      - name: upload
        run: |
          ACTIONS_VERSION=v$(jq -r .version < "$GITHUB_WORKSPACE/package.json")
          OS=$(uname | tr '[:upper:]' '[:lower:]')
          azcopy_v10 login --service-principal --application-id "$AZCOPY_SPA_APPLICATION_ID" --tenant-id "$AZCOPY_TENANT_ID"
          azcopy_v10 cp "$RUNNER_TEMP/redis-bin.tar.xz" "https://setupredis.blob.core.windows.net/actions-setup-redis/$ACTIONS_VERSION/redis-$REDIS_VERSION-${OS}-x64.tar.xz"
        env:
          REDIS_VERSION: ${{ matrix.redis }}
          AZCOPY_SPA_APPLICATION_ID: ${{ secrets.AZCOPY_SPA_APPLICATION_ID }}
          AZCOPY_SPA_CLIENT_SECRET: ${{ secrets.AZCOPY_SPA_CLIENT_SECRET }}
          AZCOPY_TENANT_ID: ${{ secrets.AZCOPY_TENANT_ID }}
