name: build-6.0

on:
  push:
    branches:
      - "releases/*"
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-20.04
          - macos-11
        redis:
          - "6.0.20"
          - "6.0.19"
          - "6.0.18"
          - "6.0.17"
          - "6.0.16"
          - "6.0.15"
          - "6.0.14"
          - "6.0.13"
          - "6.0.12"
          - "6.0.11"
          - "6.0.10"
          - "6.0.9"
          - "6.0.8"
          - "6.0.7"
          - "6.0.6"
          - "6.0.5"
          - "6.0.4"
          - "6.0.3"
          - "6.0.2"
          - "6.0.1"
          - "6.0.0"
    steps:
      - uses: actions/checkout@v4
      - name: build
        shell: bash
        run: ./build-redis-with-openssl1.1.sh "$REDIS_VERSION"
        env:
          REDIS_VERSION: ${{ matrix.redis }}

      - name: upload
        run: |
          ACTIONS_VERSION=v$(jq -r .version < "$GITHUB_WORKSPACE/package.json")
          OS=$(uname | tr '[:upper:]' '[:lower:]')
          mv "$RUNNER_TEMP/redis-bin.tar.zstd" "$RUNNER_TEMP/redis-$REDIS_VERSION-$OS-x64.tar.zstd"
          gh release upload --clobber "$ACTIONS_VERSION" "$RUNNER_TEMP/redis-$REDIS_VERSION-$OS-x64.tar.zstd"
        env:
          REDIS_VERSION: ${{ matrix.redis }}
          GITHUB_TOKEN: ${{ github.token }}
