name: "Test"
on:
  pull_request: {}
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  test:
    timeout-minutes: 13
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-24.04-arm
          - ubuntu-22.04-arm
          - ubuntu-24.04
          - ubuntu-22.04
          - ubuntu-20.04
          - macos-15
          - macos-14
          - macos-13
        redis:
          # The latest version that supports OpenSSL 1.1.1
          - "6.2"

          # Ths latest version of Redis
          - "7.2"

          # The latest version of Valkey
          - "valkey-8.0"

    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          persist-credentials: "false"

      - name: Set Node.js
        uses: actions/setup-node@cdca7365b2dadb8aad0a33bc7601856ffabcc48e # v4.3.0
        with:
          node-version-file: package.json
          cache: npm

      - run: npm ci
      - run: npm test

      - run: npm run build
      - id: setup
        name: use the action
        uses: ./
        with:
          redis-version: ${{ matrix.redis }}

      - name: connect via tcp port
        run: redis-cli -h 127.0.0.1 -p "${{ steps.setup.outputs.redis-port }}" ping
      - name: connect via unix domain socket
        run: redis-cli -s "${{ steps.setup.outputs.redis-unix-socket }}" ping

  test-tls:
    timeout-minutes: 21
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-24.04-arm
          - ubuntu-22.04-arm
          - ubuntu-24.04
          - ubuntu-22.04
          - ubuntu-20.04
          - macos-15
          - macos-14
          - macos-13
        redis:
          - "6.2"
          - "7.0"
          - "7.2"
          - "7.4"
          - "valkey-7.2"
          - "valkey-8.0"

    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          persist-credentials: "false"

      - name: Set Node.js
        uses: actions/setup-node@cdca7365b2dadb8aad0a33bc7601856ffabcc48e # v4.3.0
        with:
          node-version-file: package.json
          cache: npm

      - run: npm ci
      - run: npm run build

      # reproduce https://github.com/shogo82148/actions-setup-redis/issues/693
      - id: tmp
        run: |
          echo TEST_RUNNER_TOOL_CACHE="$(mktemp -d)" >> "$GITHUB_ENV"

      - id: setup
        name: use the action
        uses: ./
        with:
          redis-version: ${{ matrix.redis }}
          redis-port: "0"
          redis-tls-port: "6379"

      - name: connect via tls
        run: |
          redis-cli -h 127.0.0.1 -p "${{ steps.setup.outputs.redis-tls-port }}" \
            --tls \
            --cert "${{ steps.setup.outputs.redis-tls-dir }}/redis.crt" \
            --key "${{ steps.setup.outputs.redis-tls-dir }}/redis.key" \
            --cacert "${{ steps.setup.outputs.redis-tls-dir }}/ca.crt" \
            ping

  lint:
    timeout-minutes: 11
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          persist-credentials: "false"

      - name: Set Node.js
        uses: actions/setup-node@cdca7365b2dadb8aad0a33bc7601856ffabcc48e # v4.3.0
        with:
          node-version-file: package.json
          cache: npm

      - run: npm ci
      - run: npm run format-check
